#!/bin/bash
echo "--------------------cpu top 10--------------------"
ps -eo pid,pmem,pcpu --sort=-pcpu | head -n 10
echo "-------------------memmory top 10------------------"
ps -eo pid,pmem,pcpu --sort=-pcpu | head -n 10
